//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThiMINI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapHang
    {
        public int ID { get; set; }
        public string MaNhapHang { get; set; }
        public string MaMH { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public System.DateTime NgayHetHan { get; set; }
    
        public virtual MatHang MatHang { get; set; }
        public virtual NhapHang NhapHang { get; set; }
    }
}
