//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThiMINI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBanHang
    {
        public int STT { get; set; }
        public string MaMH { get; set; }
        public string MaHDBanHang { get; set; }
        public int SoLuong { get; set; }
        public double GiamGia { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual HoaDonBanHang HoaDonBanHang { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
