//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThiMINI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuyHang
    {
        public int MaHangHuy { get; set; }
        public string MaMH { get; set; }
        public int SoLuong { get; set; }
        public string LyDo { get; set; }
        public System.DateTime NgayHuy { get; set; }
        public bool Duyet { get; set; }
    
        public virtual MatHang MatHang { get; set; }
    }
}
