//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThiMINI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.ChiTietBanHangs = new HashSet<ChiTietBanHang>();
            this.ChiTietHoaDonTams = new HashSet<ChiTietHoaDonTam>();
            this.ChiTietNhapHangs = new HashSet<ChiTietNhapHang>();
            this.HangSapHetHans = new HashSet<HangSapHetHan>();
            this.HuyHangs = new HashSet<HuyHang>();
        }
    
        public string MaMH { get; set; }
        public string Nhom { get; set; }
        public string TenMH { get; set; }
        public string DonViTinh { get; set; }
        public int GiaNhap { get; set; }
        public int DonGia { get; set; }
        public double VAT { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> DonGiaSauThue { get; set; }
        public string ViTriQuay { get; set; }
        public string HinhAnh { get; set; }
        public string Barcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBanHang> ChiTietBanHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonTam> ChiTietHoaDonTams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangSapHetHan> HangSapHetHans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuyHang> HuyHangs { get; set; }
    }
}
